### ISSUE TITLE
BUG: ur:crypto-account always uses testnet derivation

### ISSUE THREAD

**Issue by craigraw** [BlockchainCommons/GordianSeedTool-iOS#116]
When using the "Authenticate/Derive Key/Other Key Derivations/Bitcoin/Mainnet/Master Key/Secondary Derivation/Account Descriptor/Share Button" the derivation path used is always for the testnet network (e.g. `m/84'/1'/0'`) regardless of the Network setting on this screen.

**Comment by wolfmcnally** [comment]
Actually the problem was that it's not picking up *changes* to the initial setting of the Network control. So if you have you default network set to Testnet, the derivation will be for Testnet even if you change the control to Mainnet. There will be a fix in Test Flight shortly.

**Comment by shannona** [comment]
Hey, @craigraw, could you confirm that the problem is fixed?

I am able to successfully import using "Gordian Seed Tool" and the account descriptor (ur:crypto-account).

I get the error 'Unrecognized Extended key header for mainnet' is I try to import either ur:crypto-account or ur:crypto-output as an Output Descriptor, but suspect maybe that input doesn't recognize URs?

If you're still seeing a problem, let us know what input mechanism you're using and what you're seeing wrong. Thanks!

**Comment by craigraw** [comment]
> Hey, @craigraw, could you confirm that the problem is fixed?

Yes, confirmed fixed.

> I get the error 'Unrecognized Extended key header for mainnet' is I try to import either ur:crypto-account or ur:crypto-output as an Output Descriptor, but suspect maybe that input doesn't recognize URs?

I'm a little unsure what you mean - the Output Descriptor option in File menu > Import does not have a Scan button? Or did you mean something else?
