### ISSUE TITLE
Support fingerprints on descriptors

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianSeedTool-iOS#145]
For reference, Sparrow has this descriptor for the Yimn Blue test seed when used as a segwit '84 account.

```
wpkh([604b93f2/84h/0h/0h]xpub6DVfq9VduocgjGeR69Nyr8CCi9w5gywnU7wXMYGswpHjffjcbLYNzz6G6555VDcSZLDwZPzJHJQabVWWgkpvYntpunL3UjHGrkCJ6VndbQf/<0;1>/*)#8hmvszgp
````

A) I believe the #8hmvszgp is the unique fingerprint for this account. If it is truly unique, we need to start using it.

B) We should document this and support it when saving account descriptors to text.

**Comment by shannona** [comment]
That's the checksum:

https://github.com/bitcoin/bitcoin/blob/master/doc/descriptors.md#checksums

It can be calculated using the bitcoin-core `getdescriptorinfo` RPC call.

**Comment by shannona** [comment]
Here's a function for the checksum:
https://github.com/bitcoin/bitcoin/blob/master/src/script/descriptor.cpp#L95

**Comment by wolfmcnally** [comment]
Fixed in next beta release.

**Comment by shannona** [comment]
The checksum now shows up on all output descriptors.

**Comment by shannona** [comment]
As far as I've been able to tell, Sparrow doesn't output descriptors.

The gold standard would be to test against getdescriptorinfo in bitcoin-cli. I can spin up an instance to check, it'll just take a bit.

**Comment by shannona** [comment]
Running through the descriptors on `bitcoin-cli`:

* Native Segwit Single Key: CHECKS
* Nested Segwit Single Key: CHECKS
* Legacy Single Key: CHECKS
* Taproot: CHECKS

The three Cosigner descriptors are not checkable because Bitcoin Core does not recognize the "cosigner" function in descriptors:
```
error code: -5
error message:
A function is needed within P2SH
```
I in fact can't find cosigner documented anywhere as a valid descriptor, not even in more extensive uses such BDK. @wolfmcnally can you reference where it came from and how standard it is?

In any case, this should be closed, but I want to make sure the compatibility question of the cosigner function is addressed by us.
