### ISSUE TITLE
CRASH: Launch of 1.4 (54) on iPod Touch 7th on 15.3.1

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianSeedTool-iOS#157]
Using Gordian Seed Tool 1.4 (54) on iPod Touch 7th on 15.3.1:

Crashed immediately on open after TestFlight download. Crashed again when opened from the springboard.

![IMG_BA1A5ADD954A-1](https://user-images.githubusercontent.com/69103/157357888-20f39cc5-1cdd-403d-890a-6cfb340ee8c8.jpeg)

Submitted crash report to Apple, name support@blockchaincommons.com

**Comment by ChristopherA** [comment]
I also tried rebooting my iPod Touch 7th, but it still crashes on open.

Note that GST worked last week on this iPod Touch 7th.

**Comment by wolfmcnally** [comment]
Based on crash logs, I determined that this is because the CoreNFC framework is missing on the iPod Touch, causing a dynamic link failure at startup. This issue has been [reported by other developers](http://www.openradar.me/FB9836080) and according to this report an iPod Touch running iOS 15.1 does not crash. As I do not have an iPod Touch to test on, the only thing I was able to do in the next build was to set the CoreNFC framework to "weak link." This may avoid the immediate crash at startup, but the app may still crash in places where it attempts to call into CoreNFC. Further crash logs for this build need to be examined to see whether anything further can be done about this.

**Comment by ChristopherA** [comment]
Is it possible to identify that there is no NFC support and the device? Will this also happen on older iPads that also don’t do NFCs?

**Comment by ChristopherA** [comment]
I tested on (55) and it doesn’t crash on launch. 

Any ideas on spots to test that might trigger other related crashes?

**Comment by ChristopherA** [comment]
In 1.4 (55) on iPod Touch 7th the NFC Button is present, disabled, and does nothing when tapped.

Minor other issue, will post separately.

I'd say that this is fixed.

**Comment by wolfmcnally** [comment]
Closing.
