### ISSUE TITLE
Sample Seed from Research Does Not Scan

### ISSUE THREAD

**Issue by shannona** [BlockchainCommons/GordianSeedTool-iOS#59]
The QR Code found in the description of the `crypto-seed` in Research does not scan:
https://github.com/BlockchainCommons/Research/blob/master/papers/bcr-2020-006-urtypes.md#cryptographic-seed-crypto-seed

(It's down at the bottom of that section.)

I get the error "CreationDate field doesn't contain a date".

The creationdate does seem to have a number, but it's a suspiciously small one
```
{1: h'c7098580125e2ab0981253468b2dbc52', 2: 100(18394)}
```

**Comment by shannona** [comment]
Testflight: 1.01 (21)

**Comment by wolfmcnally** [comment]
This was two issues:

* The stated date in [BCR-2020-006](https://github.com/BlockchainCommons/Research/blob/master/papers/bcr-2020-006-urtypes.md#exampletest-vector-1) was incorrect. It was listed as `May 13, 2020` and should have been `May 11, 2020`. [This has been fixed.](https://github.com/BlockchainCommons/Research/commit/734704b9596df7d6cd7e33beb991372d9515b38d)
* The example test vector encoded the date using the CBOR date encoding described in [RFC8943](https://datatracker.ietf.org/doc/html/rfc8943), which is an integer number of days since the Unix epoch. URKit, on the other hand, only decoded dates using the format described in [RFC8949](https://datatracker.ietf.org/doc/html/rfc8949#section-3.4.2), which is an integer or floating point number of seconds since the Unix epoch. I have added support for decoding RFC8943 dates to URKit 2.5.0 and incorporated this change into Seed Tool as of 1.0.1 (22).
